# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xci
# IP: The module: 'TFM_ZYNQ_4_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_4_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xci
# IP: The module: 'TFM_ZYNQ_4_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_4_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
