# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0.xci
# IP: The module: 'TFM_ZYNQ_4_ads_spi_ctrl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/src/fifo64x32_1/fifo64x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo64x32 || ORIG_REF_NAME==fifo64x32} -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/src/fifo64x32_1/fifo64x32.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo64x32 || ORIG_REF_NAME==fifo64x32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0.xci
# IP: The module: 'TFM_ZYNQ_4_ads_spi_ctrl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/src/fifo64x32_1/fifo64x32.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo64x32 || ORIG_REF_NAME==fifo64x32} -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_4/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/src/fifo64x32_1/fifo64x32.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo64x32 || ORIG_REF_NAME==fifo64x32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
