# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/Zybo-Z7-Master.xdc

# Block Designs: bd/TFM_ZYNQ/TFM_ZYNQ.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ || ORIG_REF_NAME==TFM_ZYNQ} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_processing_system7_0_0/TFM_ZYNQ_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==TFM_ZYNQ_processing_system7_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_axi_quad_spi_0_0 || ORIG_REF_NAME==TFM_ZYNQ_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_interconnect_0_0/TFM_ZYNQ_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_axi_interconnect_0_0 || ORIG_REF_NAME==TFM_ZYNQ_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_rst_ps7_0_50M_0/TFM_ZYNQ_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==TFM_ZYNQ_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_xlconcat_0_3/TFM_ZYNQ_xlconcat_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_xlconcat_0_3 || ORIG_REF_NAME==TFM_ZYNQ_xlconcat_0_3} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_not_irq_0_0/TFM_ZYNQ_not_irq_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_not_irq_0_0 || ORIG_REF_NAME==TFM_ZYNQ_not_irq_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ/ip/TFM_ZYNQ_auto_pc_0/TFM_ZYNQ_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_auto_pc_0 || ORIG_REF_NAME==TFM_ZYNQ_auto_pc_0} -quiet] -quiet

# XDC: bd/TFM_ZYNQ/TFM_ZYNQ_ooc.xdc
