# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0.xci
# IP: The module: 'TFM_ZYNQ_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0.xci
# IP: The module: 'TFM_ZYNQ_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/TFM/Zynq/TFM_ZINQ/TFM_ZINQ.srcs/sources_1/bd/TFM_ZYNQ/ip/TFM_ZYNQ_axi_quad_spi_0_0/TFM_ZYNQ_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TFM_ZYNQ_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
