# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Zynq/Zybo-Z7-Master.xdc

# Block Designs: bd/TFM_ZYNQ_4/TFM_ZYNQ_4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4 || ORIG_REF_NAME==TFM_ZYNQ_4} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_ads_spi_ctrl_top_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_ads_spi_ctrl_top_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_mux_0_0/TFM_ZYNQ_4_ads_spi_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_ads_spi_mux_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_ads_spi_mux_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_not_irq_0_0/TFM_ZYNQ_4_not_irq_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_not_irq_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_not_irq_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_quad_spi_0_0/TFM_ZYNQ_4_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_axi_quad_spi_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_xbar_0/TFM_ZYNQ_4_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_xbar_0 || ORIG_REF_NAME==TFM_ZYNQ_4_xbar_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ps7_0_axi_periph_0/TFM_ZYNQ_4_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_ps7_0_axi_periph_0 || ORIG_REF_NAME==TFM_ZYNQ_4_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_rst_ps7_0_50M_0/TFM_ZYNQ_4_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_rst_ps7_0_50M_0 || ORIG_REF_NAME==TFM_ZYNQ_4_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_dma_0_0/TFM_ZYNQ_4_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_axi_dma_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_axi_dma_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_mem_intercon_0/TFM_ZYNQ_4_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_axi_mem_intercon_0 || ORIG_REF_NAME==TFM_ZYNQ_4_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_xlconcat_0_0/TFM_ZYNQ_4_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_xlconcat_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_xlconcat_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ila_0_0/TFM_ZYNQ_4_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_ila_0_0 || ORIG_REF_NAME==TFM_ZYNQ_4_ila_0_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_processing_system7_0_1 || ORIG_REF_NAME==TFM_ZYNQ_4_processing_system7_0_1} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_auto_pc_0/TFM_ZYNQ_4_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_auto_pc_0 || ORIG_REF_NAME==TFM_ZYNQ_4_auto_pc_0} -quiet] -quiet

# IP: bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_auto_pc_1/TFM_ZYNQ_4_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TFM_ZYNQ_4_auto_pc_1 || ORIG_REF_NAME==TFM_ZYNQ_4_auto_pc_1} -quiet] -quiet

# XDC: bd/TFM_ZYNQ_4/TFM_ZYNQ_4_ooc.xdc
