# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.cache/wt [current_project]
set_property parent.project_path C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/victo/Desktop/TFM/Zynq/BeST_EMG_ads1298/example_dma_v0_5/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/hdl/TFM_ZYNQ_4_wrapper.vhd
add_files C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/TFM_ZYNQ_4.bd
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ads_spi_ctrl_top_0_0/src/fifo64x32_1/fifo64x32.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_quad_spi_0_0/TFM_ZYNQ_4_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_quad_spi_0_0/TFM_ZYNQ_4_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_quad_spi_0_0/TFM_ZYNQ_4_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_quad_spi_0_0/TFM_ZYNQ_4_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_xbar_0/TFM_ZYNQ_4_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_rst_ps7_0_50M_0/TFM_ZYNQ_4_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_rst_ps7_0_50M_0/TFM_ZYNQ_4_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_rst_ps7_0_50M_0/TFM_ZYNQ_4_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_dma_0_0/TFM_ZYNQ_4_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_dma_0_0/TFM_ZYNQ_4_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_axi_dma_0_0/TFM_ZYNQ_4_axi_dma_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_ila_0_0/TFM_ZYNQ_4_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_processing_system7_0_1/TFM_ZYNQ_4_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_auto_pc_0/TFM_ZYNQ_4_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/ip/TFM_ZYNQ_4_auto_pc_1/TFM_ZYNQ_4_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/sources_1/bd/TFM_ZYNQ_4/TFM_ZYNQ_4_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/constrs_1/imports/Zynq/Zybo-Z7-Master.xdc
set_property used_in_implementation false [get_files C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/constrs_1/imports/Zynq/Zybo-Z7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TFM_ZYNQ_4_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TFM_ZYNQ_4_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TFM_ZYNQ_4_wrapper_utilization_synth.rpt -pb TFM_ZYNQ_4_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
