set_property SRC_FILE_INFO {cfile:C:/Users/victo/Desktop/TFM/Zynq/TFM_ZYNQ_ETHERNET/TFM_ZYNQ_4.srcs/constrs_1/imports/Zynq/Zybo-Z7-Master.xdc rfile:../../../TFM_ZYNQ_4.srcs/constrs_1/imports/Zynq/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports SPI_MOSI]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports SPI_MISO]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports SPI_SCK]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports SPI_SS]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports ADS_DRY]
